### ISSUE TITLE
Getting OpenWeatherMapApi error while building

### ISSUE THREAD

**Issue by khat33b** [udacity/Sunshine-Version-2#159]
I am getting an error in build.gradle in the line below after downloading the final project. This is the first time I am building the project after downloading the zip file.

```
    buildTypes.each {
        it.buildConfigField 'String', 'OPEN_WEATHER_MAP_API_KEY', MyOpenWeatherMapApiKey
    }
```

The error is:

> Error:(21, 0) Could not find property 'MyOpenWeatherMapApiKey' on com.android.build.gradle.AppExtension_Decorated@28a8005d.

**Comment by exagil** [comment]
You need to generate an OpenWeatherMapApiKey from openweathermap.org and paste it at the required location

**Comment by khat33b** [comment]
That worked. Thanks!

**Comment by robophil** [comment]
Where is the required location, cos am still getting the same error after adding it

**Comment by nwaokoron** [comment]
https://github.com/udacity/Sunshine-Version-2/issues/69

hope this helps

**Comment by josegl06** [comment]
I have the same error, I added the key but still don't work
![error](https://cloud.githubusercontent.com/assets/1206857/18598990/8ea06a1e-7c1b-11e6-863f-dfb1889e0e8a.PNG)

**Comment by albaqawi** [comment]
This part of the course was poorly fixed after OpenWeathermap required to get an API key for each user.

the fix is easily found here in this post http://stackoverflow.com/questions/33226978/could-not-find-property-xxxx-on-com-android-build-gradle-appextension-decorate

either:  Create the file
~/.gradle/gradle.properties (Win: %USERPROFILE%.gradle\gradle.properties). If gradle.properties does not exist - just create it.
In the file add following line:

MyOpenWeatherMapApiKey="XXXXXXXXXXXYOUR API KEY AFTER YOU GET IT XXXXXXXXXXXXXXXXX"

OR

hard code the key in the line of code
it.buildConfigField 'String', 'OPEN_WEATHER_MAP_API_KEY', '"xxxxxxxxxxxxxxxxxx"'

The link I shared has more details.

I hope this helps.

**Comment by xuezhaojun** [comment]
before:

```
 buildTypes.each {
        it.buildConfigField 'String', 'OPEN_WEATHER_MAP_API_KEY', MyOpenWeatherMapApiKey
    }
```

after:

```
buildTypes.each {
        it.buildConfigField 'String','OPEN_WEATHER_MAP_API_KEY',"\"xx2920cbac9a6733bd9bbb8573871226\""
    }
```

**Comment by Adityareddyp** [comment]
Is this project by Udacity-Google?

**Comment by MohamedRoushdy** [comment]
@Adityareddyp Yes it is. But it sounds they don't support it anymore.
