### ISSUE TITLE
Finished 1st Section, Hardcoded Weather Data List Not Showing Up

### ISSUE THREAD

**Issue by Wingdom** [udacity/Sunshine-Version-2#250]
I finished the first section of the tutorial to the best of my ability considering the differences between the way the project is shown in the course and the way Android Studio 2.1.2 works. I split off the PlaceholderFragment class into its own .java file and left the action bar in the activity_main.xml. 

The preview in android studio looks right, but when I launch the app in the emulator, none of the fake data in my forecastArray is showing up, and I can't tell if the whole PlaceholderFragment isn't being loaded, or if just the data isn't being loaded. 

I have my code uploaded to github, https://github.com/Wingdom/Sunshine, if anyone has any suggestions on what I need to change, I would greatly appreciate it. I have been searching and searching for something I am doing wrong, and have tried several things that looked like solutions, but no change.

Emulator Screenshot: http://imgur.com/SS9bd3V
activity_main.xml Screenshot: http://imgur.com/0DPPXB3

**Comment by saladthieves** [comment]
Hi @Wingdom,

The `PlaceholderFragment` needs to be embedded properly inside your `activity_main.xml` using the `<fragment... />` tag, instead of the `<include layout="..." />` line, as follows:

```
   <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <fragment
            android:id="@+id/myFragment"
            android:name="com.example.cameronyeager.sunshine.PlaceholderFragment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            tools:layout="@layout/fragment_main" />

    </LinearLayout>

```

Using this tag tells the system (at run-time) that you have embedded a `Fragment` component inside your activity layout; and it will automatically inflate the layout file (`fragment_main.xml`) returned by the `onCreateView(LayoutInflater, ViewGroup, Bundle)` method inside the `Fragment` class (`PlaceholderFragment` in your case).

The `tools:layout` attribute is optional, and is used by Android Studio to preview the layout for your fragment as you edit.

Have a look at the [Adding a fragment to an activity](https://developer.android.com/guide/components/fragments.html#Adding) section on the android docs for more info. 

Hope that helps :wink:

**Comment by Wingdom** [comment]
Thank you @saladthieves, that is exactly what I needed, and exactly what was missing from the tutorial!
